# Generated by Django 4.2.2 on 2023-08-17 19:13

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateField(auto_now_add=True, verbose_name="Data de criação"),
                ),
                (
                    "updatedAt",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Nome"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "createdAt",
                    models.DateField(auto_now_add=True, verbose_name="Data de criação"),
                ),
                (
                    "updatedAt",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Nome")),
                (
                    "razao",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Razao Social"
                    ),
                ),
                (
                    "document",
                    core.models.DocumentField(
                        help_text="CNPJ ou CPF. Apenas dígitos.",
                        max_length=14,
                        unique=True,
                        verbose_name="Nº Documento",
                    ),
                ),
                ("is_cpf", models.BooleanField(default=False, verbose_name="CPF?")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "tel1",
                    core.models.PhoneField(
                        help_text="Ex: (85)988887777 ou (85)32221111.",
                        max_length=14,
                        verbose_name="Telefone 1",
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                ("cidade", models.CharField(max_length=20, verbose_name="Cidade")),
                (
                    "tel2",
                    core.models.PhoneField(
                        blank=True, max_length=14, verbose_name="Telefone 2"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Endereço"
                    ),
                ),
                (
                    "categoria1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category1_set",
                        to="core.category",
                    ),
                ),
                (
                    "categoria2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category2_set",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidade",
                "verbose_name_plural": "Entidades",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateField(auto_now_add=True, verbose_name="Data de criação"),
                ),
                (
                    "updatedAt",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "in_charge",
                    models.CharField(max_length=20, verbose_name="Responsável"),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Descrição"
                    ),
                ),
                (
                    "opening_h",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Horário funcionamento"
                    ),
                ),
                (
                    "opening_d",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de aberura"
                    ),
                ),
                ("wpp", models.URLField(blank=True, verbose_name="Whatsapp")),
                (
                    "website",
                    models.URLField(blank=True, max_length=100, verbose_name="Site"),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "iframe",
                    models.CharField(
                        blank=True, max_length=600, verbose_name="Iframe Google Maps"
                    ),
                ),
                ("username", core.models.UsernameField(max_length=32, unique=True)),
                (
                    "logo",
                    stdimage.models.JPEGField(
                        force_min_size=False,
                        help_text="Max size 200KB",
                        upload_to="logos/",
                        variations={},
                    ),
                ),
                (
                    "photo1",
                    stdimage.models.JPEGField(
                        blank=True,
                        force_min_size=False,
                        help_text="Max size 500KB",
                        upload_to="photos/",
                        variations={},
                    ),
                ),
                (
                    "photo2",
                    stdimage.models.JPEGField(
                        blank=True,
                        force_min_size=False,
                        help_text="Max size 500KB",
                        upload_to="photos/",
                        variations={},
                    ),
                ),
                (
                    "photo3",
                    stdimage.models.JPEGField(
                        blank=True,
                        force_min_size=False,
                        help_text="Max size 500KB",
                        upload_to="photos/",
                        variations={},
                    ),
                ),
                (
                    "photo4",
                    stdimage.models.JPEGField(
                        blank=True,
                        force_min_size=False,
                        help_text="Max size 500KB",
                        upload_to="photos/",
                        variations={},
                    ),
                ),
                (
                    "obs",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Observações"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.company",
                        verbose_name="Firma",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinante",
                "verbose_name_plural": "Assinantes",
            },
        ),
    ]
